In [1]:
import numpy as np
a=np.array([[1,2,3], [4,5,6], [7,8,9]])
print("printing array")
print()
print(a)
print("printing numpy array attributes")
print("1) array dimension:",a.ndim)
print("2) array shape:",a.shape)
print("3)array size:",a.size)
print("4) array data type:",a.dtype)
print("5) the length of each array item in bytes is:",a.itemsize)

printing array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
printing numpy array attributes
1) array dimension: 2
2) array shape: (3, 3)
3)array size: 9
4) array data type: int32
5) the length of each array item in bytes is: 4
